// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNyIzxzSbMP4GcX9oXA4_fsossL1OSS5g',
    appId: '1:404658091758:web:dd5f8ab22276fc03cd25ff',
    messagingSenderId: '404658091758',
    projectId: 'hackelite-app',
    authDomain: 'hackelite-app.firebaseapp.com',
    databaseURL: 'https://hackelite-app-default-rtdb.firebaseio.com',
    storageBucket: 'hackelite-app.appspot.com',
    measurementId: 'G-Y94RV7FZNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCztr06StCqMEnTE1sjacynmGVzLAgK4Es',
    appId: '1:404658091758:android:e2bad9c5bfb8e9d7cd25ff',
    messagingSenderId: '404658091758',
    projectId: 'hackelite-app',
    databaseURL: 'https://hackelite-app-default-rtdb.firebaseio.com',
    storageBucket: 'hackelite-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu551zAgjCcPai0B0YAwNFivj34HBbhow',
    appId: '1:404658091758:ios:dc39dc5bb6d8834dcd25ff',
    messagingSenderId: '404658091758',
    projectId: 'hackelite-app',
    databaseURL: 'https://hackelite-app-default-rtdb.firebaseio.com',
    storageBucket: 'hackelite-app.appspot.com',
    iosBundleId: 'com.hackelite.hackelite.hackElite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu551zAgjCcPai0B0YAwNFivj34HBbhow',
    appId: '1:404658091758:ios:fab2e4747166bf33cd25ff',
    messagingSenderId: '404658091758',
    projectId: 'hackelite-app',
    databaseURL: 'https://hackelite-app-default-rtdb.firebaseio.com',
    storageBucket: 'hackelite-app.appspot.com',
    iosBundleId: 'com.hackelite.hackelite.hackElite.RunnerTests',
  );
}
